/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M10
 * Generated at: 2016-10-19 09:14:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ro.dcmt.data.controllers.OperatieService;
import ro.dcmt.data.beans.Cabinet;
import ro.dcmt.data.beans.User;
import ro.dcmt.data.beans.Programare;
import ro.dcmt.data.beans.Pacient;
import ro.dcmt.data.beans.Operatie;
import ro.dcmt.data.beans.Produs;
import ro.dcmt.data.controllers.CabinetService;
import ro.dcmt.data.controllers.ProgramariService;
import ro.dcmt.data.controllers.UserService;
import ro.dcmt.data.controllers.InventarService;
import ro.dcmt.data.controllers.PacientService;
import java.util.ArrayList;
import java.util.Date;

public final class finalizeaza_002dprogramare_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("ro.dcmt.data.beans.Cabinet");
    _jspx_imports_classes.add("ro.dcmt.data.beans.Pacient");
    _jspx_imports_classes.add("ro.dcmt.data.beans.User");
    _jspx_imports_classes.add("ro.dcmt.data.beans.Produs");
    _jspx_imports_classes.add("ro.dcmt.data.controllers.UserService");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("ro.dcmt.data.beans.Operatie");
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("ro.dcmt.data.controllers.CabinetService");
    _jspx_imports_classes.add("ro.dcmt.data.beans.Programare");
    _jspx_imports_classes.add("ro.dcmt.data.controllers.PacientService");
    _jspx_imports_classes.add("ro.dcmt.data.controllers.InventarService");
    _jspx_imports_classes.add("ro.dcmt.data.controllers.OperatieService");
    _jspx_imports_classes.add("ro.dcmt.data.controllers.ProgramariService");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String email = null;
	User currentUser = new User();
	Cabinet cabinet = new Cabinet();
	UserService us = new UserService();
	PacientService ps = new PacientService();
	ProgramariService progs = new ProgramariService();
	CabinetService cs = new CabinetService();
	OperatieService os = new OperatieService();
	Cookie[] cookies = request.getCookies();
	if (cookies != null) {
		for (Cookie cookie : cookies) {
			if (cookie.getName().equals("user"))
				email = cookie.getValue();
		}
	}
	if (email == null) {
		response.sendRedirect("login.jsp");
		return;
	} else {

		currentUser = (User) us.getAllByColumn("email", email).get(0);
		cabinet = (Cabinet) cs.getById(currentUser.getId());

	}
	ArrayList<Programare> programariNoi = ProgramariService.getNewAppointmentsForDoctor(currentUser.getId());
	int programareID = Integer.parseInt(request.getParameter("programare"));
	Programare programare = (Programare) progs.getById(programareID);
	Pacient pacient = (Pacient) ps.getById(programare.getIdUser());
	ArrayList<Operatie> operatiiProgramare = os.getOperatiiForAppointment(programare.getIdOperatii());
	ArrayList<Produs> inventarDoctor = InventarService.getInventarForDoctor(currentUser.getId());
	int num = 0;

      out.write("\r\n");
      out.write("<!-- META SECTION -->\r\n");
      out.write("<title>DCMT - Finalizare programare</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("\r\n");
      out.write("<link rel=\"icon\" href=\"favicon.ico\" type=\"image/x-icon\" />\r\n");
      out.write("<!-- END META SECTION -->\r\n");
      out.write("\r\n");
      out.write("<!-- CSS INCLUDE -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" id=\"theme\"\r\n");
      out.write("\thref=\"css/theme-default.css\" />\r\n");
      out.write("<!-- EOF CSS INCLUDE -->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- START PAGE CONTAINER -->\r\n");
      out.write("\t<div class=\"page-container\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- START PAGE SIDEBAR -->\r\n");
      out.write("\t\t<div class=\"page-sidebar\">\r\n");
      out.write("\t\t\t<!-- START X-NAVIGATION -->\r\n");
      out.write("\t\t\t<ul class=\"x-navigation\">\r\n");
      out.write("\t\t\t\t<li class=\"xn-logo\"><a href=\"index.html\">DCMT - Lista\r\n");
      out.write("\t\t\t\t\t\tpacienti</a> <a href=\"#\" class=\"x-navigation-control\"></a></li>\r\n");
      out.write("\t\t\t\t<li class=\"xn-profile\"><a href=\"#\" class=\"profile-mini\"> <img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"");
      out.print(currentUser.getImagine().getName());
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\talt=\"");
      out.print(currentUser.getFirstName());
      out.write("\" />\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"profile\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"profile-image\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"");
      out.print(currentUser.getImagine().getName());
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\talt=\"");
      out.print(currentUser.getFirstName());
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"profile-data\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"profile-data-name\">\r\n");
      out.write("\t\t\t\t\t\t\t\tDr.\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(currentUser.getFirstName() + " " + currentUser.getLastName());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"profile-data-title\">");
      out.print(cabinet.getNume());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"profile-controls\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:void(0);\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonclick=\"bootstro.start('.bootstro');\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"profile-control-left\"><span class=\"fa fa-info\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"bootstro.start('.bootstro');\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"profile-control-right\"><span class=\"fa fa-envelope\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t<li class=\"xn-title\">Navigatie</li>\r\n");
      out.write("\t\t\t\t<li><a href=\"home.jsp\"><span class=\"fa fa-desktop\"></span>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"xn-text\">Privire generala</span></a></li>\r\n");
      out.write("\t\t\t\t<li class=\"xn-openable active\"><a href=\"#\"><span\r\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-files-o\"></span> <span class=\"xn-text\">Pacienti</span></a>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"pacienti.jsp\"><span class=\"fa fa-users\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\tLista Pacienti </a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"programare-noua.jsp\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-check-circle\"></span> Programare noua</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"active\"><a href=\"calendar-programari.jsp\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-calendar\"></span> Agenda programari</a></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<li class=\"xn-openable\"><a href=\"#\"><span\r\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-file-text-o\"></span> <span class=\"xn-text\">Cabinet</span></a>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"layout-nav-top.html\">Agenda programari</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"layout-boxed.html\">Stoc produse</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"layout-nav-toggled.html\">Furnizori</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"layout-nav-top.html\">Plati utilitare</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<!-- END X-NAVIGATION -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- END PAGE SIDEBAR -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- PAGE CONTENT -->\r\n");
      out.write("\t\t<div class=\"page-content\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- START X-NAVIGATION VERTICAL -->\r\n");
      out.write("\t\t\t<ul class=\"x-navigation x-navigation-horizontal x-navigation-panel\">\r\n");
      out.write("\t\t\t\t<!-- TOGGLE NAVIGATION -->\r\n");
      out.write("\t\t\t\t<li class=\"xn-icon-button\"><a href=\"#\"\r\n");
      out.write("\t\t\t\t\tclass=\"x-navigation-minimize\"><span class=\"fa fa-dedent\"></span></a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<!-- END TOGGLE NAVIGATION -->\r\n");
      out.write("\t\t\t\t<!-- SEARCH -->\r\n");
      out.write("\t\t\t\t<li class=\"xn-search\">\r\n");
      out.write("\t\t\t\t\t<form role=\"form\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"search\" placeholder=\"Cauta pacienti...\" />\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<!-- END SEARCH -->\r\n");
      out.write("\t\t\t\t<!-- SIGN OUT -->\r\n");
      out.write("\t\t\t\t<li class=\"xn-icon-button pull-right\"><a href=\"#\"\r\n");
      out.write("\t\t\t\t\tclass=\"mb-control\" data-box=\"#mb-signout\"><span\r\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-sign-out\"></span></a></li>\r\n");
      out.write("\t\t\t\t<!-- END SIGN OUT -->\r\n");
      out.write("\t\t\t\t<!-- MESSAGES -->\r\n");
      out.write("\t\t\t\t<li class=\"xn-icon-button pull-right\"><a href=\"#\"><span\r\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-calendar-check-o\"></span></a>\r\n");
      out.write("\t\t\t\t\t<div class=\"informer informer-danger\">");
      out.print(programariNoi.size());
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\tclass=\"panel panel-primary animated zoomIn xn-drop-left xn-panel-dragging\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"panel-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"fa fa-calendar-check-o\"></span> Programari noi\r\n");
      out.write("\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"pull-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"label label-danger\">");
      out.print(programariNoi.size());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\tneaprobate</span>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-body list-group list-group-contacts scroll\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"height: 200px;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");

								Pacient pacientProgramare;
								for (Programare p : programariNoi) {

									pacientProgramare = (Pacient) ps.getById(p.getIdUser());
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"pacient.jsp?id=");
      out.print(pacientProgramare.getId());
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"list-group-item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"list-group-status status-online\"></div> <img\r\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"");
      out.print(pacientProgramare.getImagine().getName());
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"pull-left\" alt=\"");
      out.print(pacientProgramare.getFirstName());
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"contacts-title\">");
      out.print(pacientProgramare.getFirstName() + " " + pacientProgramare.getLastName());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p>");
      out.print(p.getIdOperatii());
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-footer text-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"pages-messages.html\">Vezi toate programarile</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t<!-- END MESSAGES -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<!-- END X-NAVIGATION VERTICAL -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- START BREADCRUMB -->\r\n");
      out.write("\t\t\t<ul class=\"breadcrumb\">\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">Acasa</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">Pacienti</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">Programare</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"active\">Finalizeaza programare</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<!-- END BREADCRUMB -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- PAGE CONTENT WRAPPER -->\r\n");
      out.write("\t\t\t<div class=\"page-content-wrap\">\r\n");
      out.write("\t\t\t\t<!-- START WIZARD WITH SUBMIT BUTTON -->\r\n");
      out.write("\t\t\t\t<div class=\"block\">\r\n");
      out.write("\t\t\t\t\t<h4>Finalizare programare</h4>\r\n");
      out.write("\t\t\t\t\t<form\r\n");
      out.write("\t\t\t\t\t\taction=\"javascript:endAppointment(");
      out.print(operatiiProgramare.size());
      out.write(',');
      out.print(currentUser.getId());
      out.write(',');
      out.print(programare.getId());
      out.write(")\"\r\n");
      out.write("\t\t\t\t\t\trole=\"form\" class=\"form-horizontal\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"wizard show-submit\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#step-1\"> <span class=\"stepNumber\">1</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"stepDesc\">Pacient<br /> <small>Date\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tpersonale</small></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#step-2\"> <span class=\"stepNumber\">2</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"stepDesc\">Stocuri<br /> <small>Actualizare\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tstocuri</small></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#step-3\"> <span class=\"stepNumber\">3</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"stepDesc\">Facturare<br /> <small>Optiuni\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tde facturare</small></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"step-1\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"col-md-2 control-label\">Nume</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" readonly\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Ion\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(pacient.getFirstName() + " " + pacient.getLastName());
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"numePacient\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"col-md-2 control-label\">Oras</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Bucuresti\" id=\"orasPacient\" readonly\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(pacient.getCity());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"col-md-2 control-label\">Email</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"ion.popescu@gmail.com\" id=\"emailPacient\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\treadonly value=\"");
      out.print(pacient.getEmail());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"col-md-2 control-label\">Numar de telefon</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"0722 222 222\" id=\"numarTelefonPacient\" readonly\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(pacient.getPhoneNumber());
      out.write(" \">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"step-2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<br />\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<br /> <br />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										for (Operatie operatie : operatiiProgramare) {
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!-- PANEL OPERATIE -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"panel panel-warning\" id=\"operatie\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"panel-heading ui-draggable-handle\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3 class=\"panel-title\">");
      out.print(operatie.getTitlu());
      out.write("</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"panel-controls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"panel-fullscreen\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-expand\"></span></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\" class=\"panel-collapse\"><span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-angle-down\"></span></a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<label class=\"col-md-2 control-label\">Produse</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-9\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<select multiple class=\"form-control select\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tdata-live-search=\"true\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"produseOperatie");
      out.print(operatie.getId());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");

														for (Produs produs : inventarDoctor) {
													
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<option class=\"productOption\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(operatie.getId());
      out.write(',');
      out.print(produs.getID());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(produs.getNumeProdus());
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t");

														}
													
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"panel-footer\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<!--  END PANEL OPERATIE -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										}
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"step-3\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"switch\"> Genereaza factura      <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"checkbox\" onClick=\"showPrice()\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"generateInvoice\" /> <span></span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\" style=\"display: none\" id=\"pretDiv\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"col-md-2 control-label\">Pret total:</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-4    \">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"validate[required,custom[integer],min[1] form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"pret\" /> <span class=\"help-block\">Valoare minima\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t1</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-4\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"switch\"> Trimite factura prin Email pacientului     <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tid=\"sendInvoice\" /> <span></span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- END WIZARD WITH SUBMIT BUTTON -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- END PAGE CONTENT WRAPPER -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- END PAGE CONTENT -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- END PAGE CONTAINER -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- MESSAGE BOX-->\r\n");
      out.write("\t<div class=\"message-box animated fadeIn\" data-sound=\"alert\"\r\n");
      out.write("\t\tid=\"mb-signout\">\r\n");
      out.write("\t\t<div class=\"mb-container\">\r\n");
      out.write("\t\t\t<div class=\"mb-middle\">\r\n");
      out.write("\t\t\t\t<div class=\"mb-title\">\r\n");
      out.write("\t\t\t\t\t<span class=\"fa fa-sign-out\"></span> Log <strong>Out</strong> ?\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"mb-content\">\r\n");
      out.write("\t\t\t\t\t<p>Are you sure you want to log out?</p>\r\n");
      out.write("\t\t\t\t\t<p>Press No if youwant to continue work. Press Yes to logout\r\n");
      out.write("\t\t\t\t\t\tcurrent user.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"mb-footer\">\r\n");
      out.write("\t\t\t\t\t<div class=\"pull-right\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"pages-login.html\" class=\"btn btn-success btn-lg\">Yes</a>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-default btn-lg mb-control-close\">No</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- END MESSAGE BOX-->\r\n");
      out.write("\r\n");
      out.write("\t<!-- START PRELOADS -->\r\n");
      out.write("\t<audio id=\"audio-alert\" src=\"audio/alert.mp3\" preload=\"auto\"></audio>\r\n");
      out.write("\t<audio id=\"audio-fail\" src=\"audio/fail.mp3\" preload=\"auto\"></audio>\r\n");
      out.write("\t<!-- END PRELOADS -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- START SCRIPTS -->\r\n");
      out.write("\t<!-- START PLUGINS -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/plugins/jquery/jquery.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/plugins/jquery/jquery-ui.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"js/plugins/bootstrap/bootstrap.min.js\"></script>\r\n");
      out.write("\t<!-- END PLUGINS -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- THIS PAGE PLUGINS -->\r\n");
      out.write("\t<script type='text/javascript' src='js/plugins/icheck/icheck.min.js'></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"js/plugins/bootstrap/bootstrap-datepicker.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"js/plugins/bootstrap/bootstrap-file-input.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"js/plugins/bootstrap/bootstrap-select.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"js/plugins/tagsinput/jquery.tagsinput.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\"\r\n");
      out.write("\t\tsrc=\"js/plugins/smartwizard/jquery.smartWizard-2.0.min.js\"></script>\r\n");
      out.write("\t<script type='text/javascript'\r\n");
      out.write("\t\tsrc='js/plugins/jquery-validation/jquery.validate.js'></script>\r\n");
      out.write("\t<!-- END THIS PAGE PLUGINS -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- START TEMPLATE -->\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/finalizeaza-programare.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/plugins.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/actions.js\"></script>\r\n");
      out.write("\t<!-- END TEMPLATE -->\r\n");
      out.write("\t<!-- END SCRIPTS -->\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar jvalidate = $(\"#jvalidate\").validate({\r\n");
      out.write("\t\t\tignore : [],\r\n");
      out.write("\t\t\trules : {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tpret : {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tmin : 1\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
