/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M10
 * Generated at: 2016-10-17 11:33:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ro.dcmt.data.beans.Cabinet;
import ro.dcmt.data.beans.User;
import ro.dcmt.data.beans.Programare;
import ro.dcmt.data.beans.Pacient;
import ro.dcmt.data.controllers.CabinetService;
import ro.dcmt.data.controllers.ProgramariService;
import ro.dcmt.data.controllers.UserService;
import ro.dcmt.data.controllers.PacientService;
import java.util.ArrayList;
import java.util.Date;

public final class pages_002dcalendar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("ro.dcmt.data.beans.Cabinet");
    _jspx_imports_classes.add("ro.dcmt.data.beans.Pacient");
    _jspx_imports_classes.add("ro.dcmt.data.controllers.CabinetService");
    _jspx_imports_classes.add("ro.dcmt.data.beans.Programare");
    _jspx_imports_classes.add("ro.dcmt.data.beans.User");
    _jspx_imports_classes.add("ro.dcmt.data.controllers.UserService");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("ro.dcmt.data.controllers.PacientService");
    _jspx_imports_classes.add("ro.dcmt.data.controllers.ProgramariService");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	String email = null;
	User currentUser = new User();
	Cabinet cabinet = new Cabinet();
	UserService us = new UserService();
	PacientService ps = new PacientService();
	ProgramariService progs = new ProgramariService();
	CabinetService cs = new CabinetService();
	Cookie[] cookies = request.getCookies();
	if (cookies != null) {
		for (Cookie cookie : cookies) {
			if (cookie.getName().equals("user"))
				email = cookie.getValue();
		}
	}
	if (email == null) {
		response.sendRedirect("login.jsp");
		return;
	} else {

		currentUser = (User) us.getAllByColumn("email", email).get(0);
		cabinet = (Cabinet) cs.getById(currentUser.getId());

	}
	ArrayList<Programare> programariNoi = ProgramariService.getNewAppointmentsForDoctor(currentUser.getId());
	ArrayList<Programare> programariViitoare = ProgramariService.getFutureAppointments(currentUser.getId());
	
	 



      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- META SECTION -->\n");
      out.write("<title>Atlant - Responsive Bootstrap Admin Template</title>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n");
      out.write("\n");
      out.write("<link rel=\"icon\" href=\"favicon.ico\" type=\"image/x-icon\" />\n");
      out.write("<!-- END META SECTION -->\n");
      out.write("\n");
      out.write("<!-- CSS INCLUDE -->\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" id=\"theme\"\n");
      out.write("\thref=\"css/theme-default.css\" />\n");
      out.write("<!-- EOF CSS INCLUDE -->\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<!-- START PAGE CONTAINER -->\n");
      out.write("\t<div class=\"page-container\">\n");
      out.write("\n");
      out.write("\t\t<!-- START PAGE SIDEBAR -->\n");
      out.write("\t\t<div class=\"page-sidebar\">\n");
      out.write("\t\t\t<!-- START X-NAVIGATION -->\n");
      out.write("\t\t\t<ul class=\"x-navigation\">\n");
      out.write("\t\t\t\t<li class=\"xn-logo\"><a href=\"index.html\">ATLANT</a> <a href=\"#\"\n");
      out.write("\t\t\t\t\tclass=\"x-navigation-control\"></a></li>\n");
      out.write("\t\t\t\t<li class=\"xn-profile\"><a href=\"#\" class=\"profile-mini\"> <img\n");
      out.write("\t\t\t\t\t\tsrc=\"assets/images/users/avatar.jpg\" alt=\"John Doe\" />\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t<div class=\"profile\">\n");
      out.write("\t\t\t\t\t\t<div class=\"profile-image\">\n");
      out.write("\t\t\t\t\t\t\t<img src=\"assets/images/users/avatar.jpg\" alt=\"John Doe\" />\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"profile-data\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"profile-data-name\">John Doe</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"profile-data-title\">Web Developer/Designer</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"profile-controls\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"pages-profile.html\" class=\"profile-control-left\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-info\"></span></a> <a href=\"pages-messages.html\"\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"profile-control-right\"><span class=\"fa fa-envelope\"></span></a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div></li>\n");
      out.write("\t\t\t\t<li class=\"xn-title\">Navigation</li>\n");
      out.write("\t\t\t\t<li><a href=\"index.html\"><span class=\"fa fa-desktop\"></span>\n");
      out.write("\t\t\t\t\t\t<span class=\"xn-text\">Dashboard</span></a></li>\n");
      out.write("\t\t\t\t<li class=\"xn-openable active\"><a href=\"#\"><span\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-files-o\"></span> <span class=\"xn-text\">Pages</span></a>\n");
      out.write("\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"pages-gallery.html\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-image\"></span> Gallery</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"pages-profile.html\"><span class=\"fa fa-user\"></span>\n");
      out.write("\t\t\t\t\t\t\t\tProfile</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"pages-address-book.html\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-users\"></span> Address Book</a></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"xn-openable\"><a href=\"#\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-clock-o\"></span> Timeline</a>\n");
      out.write("\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"pages-timeline.html\"><span\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-align-center\"></span> Default</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"pages-timeline-simple.html\"><span\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-align-justify\"></span> Full Width</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"xn-openable\"><a href=\"#\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-envelope\"></span> Mailbox</a>\n");
      out.write("\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"pages-mailbox-inbox.html\"><span\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-inbox\"></span> Inbox</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"pages-mailbox-message.html\"><span\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-file-text\"></span> Message</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"pages-mailbox-compose.html\"><span\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-pencil\"></span> Compose</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"pages-messages.html\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-comments\"></span> Messages</a></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"active\"><a href=\"pages-calendar.html\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-calendar\"></span> Calendar</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"pages-tasks.html\"><span class=\"fa fa-edit\"></span>\n");
      out.write("\t\t\t\t\t\t\t\tTasks</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"pages-content-table.html\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-columns\"></span> Content Table</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"pages-faq.html\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-question-circle\"></span> FAQ</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"pages-search.html\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-search\"></span> Search</a></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"xn-openable\"><a href=\"#\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-file\"></span> Blog</a>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"pages-blog-list.html\"><span\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-copy\"></span> List of Posts</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"pages-blog-post.html\"><span\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-file-o\"></span>Single Post</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"xn-openable\"><a href=\"#\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-sign-in\"></span> Login</a>\n");
      out.write("\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"pages-login.html\">App Login</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"pages-login-website.html\">Website Login</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"pages-login-website-light.html\"> Website\n");
      out.write("\t\t\t\t\t\t\t\t\t\tLogin Light</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"xn-openable\"><a href=\"#\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-warning\"></span> Error Pages</a>\n");
      out.write("\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"pages-error-404.html\">Error 404 Sample 1</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"pages-error-404-2.html\">Error 404 Sample 2</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"pages-error-500.html\"> Error 500</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t<li class=\"xn-openable\"><a href=\"#\"><span\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-file-text-o\"></span> <span class=\"xn-text\">Layouts</span></a>\n");
      out.write("\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"layout-boxed.html\">Boxed</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"layout-nav-toggled.html\">Navigation Toggled</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"layout-nav-top.html\">Navigation Top</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"layout-nav-right.html\">Navigation Right</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"layout-nav-top-fixed.html\">Top Navigation\n");
      out.write("\t\t\t\t\t\t\t\tFixed</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"layout-nav-custom.html\">Custom Navigation</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"layout-frame-left.html\">Frame Left Column</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"layout-frame-right.html\">Frame Right Column</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"layout-search-left.html\">Search Left Side</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"blank.html\">Blank Page</a></li>\n");
      out.write("\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t<li class=\"xn-title\">Components</li>\n");
      out.write("\t\t\t\t<li class=\"xn-openable\"><a href=\"#\"><span\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-cogs\"></span> <span class=\"xn-text\">UI Kits</span></a>\n");
      out.write("\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"ui-widgets.html\"><span class=\"fa fa-heart\"></span>\n");
      out.write("\t\t\t\t\t\t\t\tWidgets</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"ui-elements.html\"><span class=\"fa fa-cogs\"></span>\n");
      out.write("\t\t\t\t\t\t\t\tElements</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"ui-buttons.html\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-square-o\"></span> Buttons</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"ui-panels.html\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-pencil-square-o\"></span> Panels</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"ui-icons.html\"><span class=\"fa fa-magic\"></span>\n");
      out.write("\t\t\t\t\t\t\t\tIcons</a>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"informer informer-warning\">+679</div></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"ui-typography.html\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-pencil\"></span> Typography</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"ui-portlet.html\"><span class=\"fa fa-th\"></span>\n");
      out.write("\t\t\t\t\t\t\t\tPortlet</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"ui-sliders.html\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-arrows-h\"></span> Sliders</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"ui-alerts-popups.html\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-warning\"></span> Alerts & Popups</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"ui-lists.html\"><span class=\"fa fa-list-ul\"></span>\n");
      out.write("\t\t\t\t\t\t\t\tLists</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"ui-tour.html\"><span class=\"fa fa-random\"></span>\n");
      out.write("\t\t\t\t\t\t\t\tTour</a></li>\n");
      out.write("\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t<li class=\"xn-openable\"><a href=\"#\"><span\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-pencil\"></span> <span class=\"xn-text\">Forms</span></a>\n");
      out.write("\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"form-layouts-two-column.html\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-tasks\"></span> Form Layouts</a>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"informer informer-danger\">New</div>\n");
      out.write("\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"form-layouts-one-column.html\"><span\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-align-justify\"></span> One Column</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"form-layouts-two-column.html\"><span\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-th-large\"></span> Two Column</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"form-layouts-tabbed.html\"><span\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-table\"></span> Tabbed</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"form-layouts-separated.html\"><span\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-th-list\"></span> Separated Rows</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"form-elements.html\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-file-text-o\"></span> Elements</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"form-validation.html\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-list-alt\"></span> Validation</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"form-wizards.html\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-arrow-right\"></span> Wizards</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"form-editors.html\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-text-width\"></span> WYSIWYG Editors</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"form-file-handling.html\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-floppy-o\"></span> File Handling</a></li>\n");
      out.write("\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t<li class=\"xn-openable\"><a href=\"tables.html\"><span\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-table\"></span> <span class=\"xn-text\">Tables</span></a>\n");
      out.write("\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"table-basic.html\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-align-justify\"></span> Basic</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"table-datatables.html\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-sort-alpha-desc\"></span> Data Tables</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"table-export.html\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-download\"></span> Export Tables</a></li>\n");
      out.write("\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t<li class=\"xn-openable\"><a href=\"#\"><span\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-bar-chart-o\"></span> <span class=\"xn-text\">Charts</span></a>\n");
      out.write("\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"charts-morris.html\"><span class=\"xn-text\">Morris</span></a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"charts-nvd3.html\"><span class=\"xn-text\">NVD3</span></a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"charts-rickshaw.html\"><span class=\"xn-text\">Rickshaw</span></a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"charts-other.html\"><span class=\"xn-text\">Other</span></a></li>\n");
      out.write("\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t<li><a href=\"maps.html\"><span class=\"fa fa-map-marker\"></span>\n");
      out.write("\t\t\t\t\t\t<span class=\"xn-text\">Maps</span></a></li>\n");
      out.write("\t\t\t\t<li class=\"xn-openable\"><a href=\"#\"><span\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-sitemap\"></span> <span class=\"xn-text\">Navigation\n");
      out.write("\t\t\t\t\t\t\tLevels</span></a>\n");
      out.write("\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t<li class=\"xn-openable\"><a href=\"#\">Second Level</a>\n");
      out.write("\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"xn-openable\"><a href=\"#\">Third Level</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"xn-openable\"><a href=\"#\">Fourth Level</a>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\">Fifth Level</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t\t</ul></li>\n");
      out.write("\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t\t<!-- END X-NAVIGATION -->\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- END PAGE SIDEBAR -->\n");
      out.write("\n");
      out.write("\t\t<!-- PAGE CONTENT -->\n");
      out.write("\t\t<div class=\"page-content\">\n");
      out.write("\n");
      out.write("\t\t\t<!-- START X-NAVIGATION VERTICAL -->\n");
      out.write("\t\t\t<ul class=\"x-navigation x-navigation-horizontal x-navigation-panel\">\n");
      out.write("\t\t\t\t<!-- TOGGLE NAVIGATION -->\n");
      out.write("\t\t\t\t<li class=\"xn-icon-button\"><a href=\"#\"\n");
      out.write("\t\t\t\t\tclass=\"x-navigation-minimize\"><span class=\"fa fa-dedent\"></span></a>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t<!-- END TOGGLE NAVIGATION -->\n");
      out.write("\t\t\t\t<!-- SEARCH -->\n");
      out.write("\t\t\t\t<li class=\"xn-search\">\n");
      out.write("\t\t\t\t\t<form role=\"form\">\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"search\" placeholder=\"Search...\" />\n");
      out.write("\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t<!-- END SEARCH -->\n");
      out.write("\t\t\t\t<!-- SIGN OUT -->\n");
      out.write("\t\t\t\t<li class=\"xn-icon-button pull-right\"><a href=\"#\"\n");
      out.write("\t\t\t\t\tclass=\"mb-control\" data-box=\"#mb-signout\"><span\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-sign-out\"></span></a></li>\n");
      out.write("\t\t\t\t<!-- END SIGN OUT -->\n");
      out.write("\t\t\t\t<!-- MESSAGES -->\n");
      out.write("\t\t\t\t<li class=\"xn-icon-button pull-right\"><a href=\"#\"><span\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-comments\"></span></a>\n");
      out.write("\t\t\t\t\t<div class=\"informer informer-danger\">4</div>\n");
      out.write("\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\tclass=\"panel panel-primary animated zoomIn xn-drop-left xn-panel-dragging\">\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-heading\">\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"panel-title\">\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"fa fa-comments\"></span> Messages\n");
      out.write("\t\t\t\t\t\t\t</h3>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"pull-right\">\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"label label-danger\">4 new</span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-body list-group list-group-contacts scroll\"\n");
      out.write("\t\t\t\t\t\t\tstyle=\"height: 200px;\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"list-group-item\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"list-group-status status-online\"></div> <img\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"assets/images/users/user2.jpg\" class=\"pull-left\"\n");
      out.write("\t\t\t\t\t\t\t\talt=\"John Doe\" /> <span class=\"contacts-title\">John Doe</span>\n");
      out.write("\t\t\t\t\t\t\t\t<p>Praesent placerat tellus id augue condimentum</p>\n");
      out.write("\t\t\t\t\t\t\t</a> <a href=\"#\" class=\"list-group-item\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"list-group-status status-away\"></div> <img\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"assets/images/users/user.jpg\" class=\"pull-left\"\n");
      out.write("\t\t\t\t\t\t\t\talt=\"Dmitry Ivaniuk\" /> <span class=\"contacts-title\">Dmitry\n");
      out.write("\t\t\t\t\t\t\t\t\tIvaniuk</span>\n");
      out.write("\t\t\t\t\t\t\t\t<p>Donec risus sapien, sagittis et magna quis</p>\n");
      out.write("\t\t\t\t\t\t\t</a> <a href=\"#\" class=\"list-group-item\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"list-group-status status-away\"></div> <img\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"assets/images/users/user3.jpg\" class=\"pull-left\"\n");
      out.write("\t\t\t\t\t\t\t\talt=\"Nadia Ali\" /> <span class=\"contacts-title\">Nadia\n");
      out.write("\t\t\t\t\t\t\t\t\tAli</span>\n");
      out.write("\t\t\t\t\t\t\t\t<p>Mauris vel eros ut nunc rhoncus cursus sed</p>\n");
      out.write("\t\t\t\t\t\t\t</a> <a href=\"#\" class=\"list-group-item\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"list-group-status status-offline\"></div> <img\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"assets/images/users/user6.jpg\" class=\"pull-left\"\n");
      out.write("\t\t\t\t\t\t\t\talt=\"Darth Vader\" /> <span class=\"contacts-title\">Darth\n");
      out.write("\t\t\t\t\t\t\t\t\tVader</span>\n");
      out.write("\t\t\t\t\t\t\t\t<p>I want my money back!</p>\n");
      out.write("\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-footer text-center\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"pages-messages.html\">Show all messages</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div></li>\n");
      out.write("\t\t\t\t<!-- END MESSAGES -->\n");
      out.write("\t\t\t\t<!-- TASKS -->\n");
      out.write("\t\t\t\t<li class=\"xn-icon-button pull-right\"><a href=\"#\"><span\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-tasks\"></span></a>\n");
      out.write("\t\t\t\t\t<div class=\"informer informer-warning\">3</div>\n");
      out.write("\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\tclass=\"panel panel-primary animated zoomIn xn-drop-left xn-panel-dragging\">\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-heading\">\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"panel-title\">\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"fa fa-tasks\"></span> Tasks\n");
      out.write("\t\t\t\t\t\t\t</h3>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"pull-right\">\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"label label-warning\">3 active</span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-body list-group scroll\" style=\"height: 200px;\">\n");
      out.write("\t\t\t\t\t\t\t<a class=\"list-group-item\" href=\"#\"> <strong>Phasellus\n");
      out.write("\t\t\t\t\t\t\t\t\taugue arcu, elementum</strong>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"progress progress-small progress-striped active\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"progress-bar progress-bar-danger\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\trole=\"progressbar\" aria-valuenow=\"50\" aria-valuemin=\"0\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\taria-valuemax=\"100\" style=\"width: 50%;\">50%</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div> <small class=\"text-muted\">John Doe, 25 Sep 2014 / 50%</small>\n");
      out.write("\t\t\t\t\t\t\t</a> <a class=\"list-group-item\" href=\"#\"> <strong>Aenean\n");
      out.write("\t\t\t\t\t\t\t\t\tac cursus</strong>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"progress progress-small progress-striped active\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"progress-bar progress-bar-warning\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\trole=\"progressbar\" aria-valuenow=\"80\" aria-valuemin=\"0\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\taria-valuemax=\"100\" style=\"width: 80%;\">80%</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div> <small class=\"text-muted\">Dmitry Ivaniuk, 24 Sep 2014 /\n");
      out.write("\t\t\t\t\t\t\t\t\t80%</small>\n");
      out.write("\t\t\t\t\t\t\t</a> <a class=\"list-group-item\" href=\"#\"> <strong>Lorem\n");
      out.write("\t\t\t\t\t\t\t\t\tipsum dolor</strong>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"progress progress-small progress-striped active\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"progress-bar progress-bar-success\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\trole=\"progressbar\" aria-valuenow=\"95\" aria-valuemin=\"0\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\taria-valuemax=\"100\" style=\"width: 95%;\">95%</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div> <small class=\"text-muted\">John Doe, 23 Sep 2014 / 95%</small>\n");
      out.write("\t\t\t\t\t\t\t</a> <a class=\"list-group-item\" href=\"#\"> <strong>Cras\n");
      out.write("\t\t\t\t\t\t\t\t\tsuscipit ac quam at tincidunt.</strong>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"progress progress-small\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"progress-bar\" role=\"progressbar\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\taria-valuenow=\"100\" aria-valuemin=\"0\" aria-valuemax=\"100\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"width: 100%;\">100%</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div> <small class=\"text-muted\">John Doe, 21 Sep 2014 /</small><small\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"text-success\"> Done</small>\n");
      out.write("\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-footer text-center\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"pages-tasks.html\">Show all tasks</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div></li>\n");
      out.write("\t\t\t\t<!-- END TASKS -->\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t\t<!-- END X-NAVIGATION VERTICAL -->\n");
      out.write("\n");
      out.write("\t\t\t<!-- START BREADCRUMB -->\n");
      out.write("\t\t\t<ul class=\"breadcrumb push-down-0\">\n");
      out.write("\t\t\t\t<li><a href=\"home.jsp\">Acasa</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"#\">Pacienti</a></li>\n");
      out.write("\t\t\t\t<li class=\"active\">Programari</li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t\t<!-- END BREADCRUMB -->\n");
      out.write("\n");
      out.write("\t\t\t<!-- START CONTENT FRAME -->\n");
      out.write("\t\t\t<div class=\"content-frame\">\n");
      out.write("\t\t\t\t<!-- START CONTENT FRAME TOP -->\n");
      out.write("\t\t\t\t<div class=\"content-frame-top\">\n");
      out.write("\t\t\t\t\t<div class=\"page-title\">\n");
      out.write("\t\t\t\t\t\t<h2>\n");
      out.write("\t\t\t\t\t\t\t<span class=\"fa fa-calendar\"></span> Calendar programari\n");
      out.write("\t\t\t\t\t\t</h2>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"pull-right\">\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-default content-frame-left-toggle\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"fa fa-bars\"></span>\n");
      out.write("\t\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!-- END CONTENT FRAME TOP -->\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- START CONTENT FRAME LEFT -->\n");
      out.write("\t\t\t\t<div class=\"content-frame-left\">\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<h4>Informatii</h4>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"panel panel-default push-up-10\">\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-body padding-top-0\">\n");
      out.write("\t\t\t\t\t\t\t<h4>Despre programari</h4>\n");
      out.write("\t\t\t\t\t\t\t<p>Acest modul va permite sa vizualizati programarile pe care le aveti intr-un calendar dinamic.</p>\n");
      out.write("\t\t\t\t\t\t\t<p>Total programari viitoare: <b>");
      out.print(programariViitoare.size() );
      out.write("</b></p>\n");
      out.write("\t\t\t\t\t\t\t<p>Total programari neaprobate: <b>");
      out.print(programariNoi.size() );
      out.write("</b></p>\n");
      out.write("\t\t\t\t\t\t\t<p>Total programari in agenda: <b>");
      out.print(ProgramariService.getCountofAppointmentsForDoctor(currentUser.getId()));
      out.write("</b></p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!-- END CONTENT FRAME LEFT -->\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"doctorID\"\n");
      out.write("\t\t\t\t\tvalue=\"");
      out.print(currentUser.getId());
      out.write("\"/>\n");
      out.write("\t\t\t\t<!-- START CONTENT FRAME BODY -->\n");
      out.write("\t\t\t\t<div class=\"content-frame-body padding-bottom-0\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12\">\n");
      out.write("\t\t\t\t\t\t\t<div id=\"alert_holder\"></div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"calendar\">\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"calendar\"></div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!-- END CONTENT FRAME BODY -->\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- END CONTENT FRAME -->\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- END PAGE CONTENT -->\n");
      out.write("\t</div>\n");
      out.write("\t<!-- END PAGE CONTAINER -->\n");
      out.write("\n");
      out.write("\t<!-- MESSAGE BOX-->\n");
      out.write("\t<div class=\"message-box animated fadeIn\" data-sound=\"alert\"\n");
      out.write("\t\tid=\"mb-signout\">\n");
      out.write("\t\t<div class=\"mb-container\">\n");
      out.write("\t\t\t<div class=\"mb-middle\">\n");
      out.write("\t\t\t\t<div class=\"mb-title\">\n");
      out.write("\t\t\t\t\t<span class=\"fa fa-sign-out\"></span> Log <strong>Out</strong> ?\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"mb-content\">\n");
      out.write("\t\t\t\t\t<p>Are you sure you want to log out?</p>\n");
      out.write("\t\t\t\t\t<p>Press No if youwant to continue work. Press Yes to logout\n");
      out.write("\t\t\t\t\t\tcurrent user.</p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"mb-footer\">\n");
      out.write("\t\t\t\t\t<div class=\"pull-right\">\n");
      out.write("\t\t\t\t\t\t<a href=\"pages-login.html\" class=\"btn btn-success btn-lg\">Yes</a>\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-default btn-lg mb-control-close\">No</button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- END MESSAGE BOX-->\n");
      out.write("\n");
      out.write("\t<!-- START PRELOADS -->\n");
      out.write("\t<audio id=\"audio-alert\" src=\"audio/alert.mp3\" preload=\"auto\"></audio>\n");
      out.write("\t<audio id=\"audio-fail\" src=\"audio/fail.mp3\" preload=\"auto\"></audio>\n");
      out.write("\t<!-- END PRELOADS -->\n");
      out.write("\n");
      out.write("\t<!-- START SCRIPTS -->\n");
      out.write("\t<!-- START PLUGINS -->\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/plugins/jquery/jquery.min.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/plugins/jquery/jquery-ui.min.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\"\n");
      out.write("\t\tsrc=\"js/plugins/bootstrap/bootstrap.min.js\"></script>\n");
      out.write("\t<!-- END PLUGINS -->\n");
      out.write("\n");
      out.write("\t<!-- START THIS PAGE PLUGINS-->\n");
      out.write("\t<script type='text/javascript' src='js/plugins/icheck/icheck.min.js'></script>\n");
      out.write("\t<script type=\"text/javascript\"\n");
      out.write("\t\tsrc=\"js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js\"></script>\n");
      out.write("\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/plugins/moment.min.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\"\n");
      out.write("\t\tsrc=\"js/plugins/fullcalendar/fullcalendar.min.js\"></script>\n");
      out.write("\t<!-- END THIS PAGE PLUGINS-->\n");
      out.write("\n");
      out.write("\t<!-- START TEMPLATE -->\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/calendar-programari.js\"></script>\n");
      out.write("\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/plugins.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/actions.js\"></script>\n");
      out.write("\t<!-- END TEMPLATE -->\n");
      out.write("\n");
      out.write("\t<!-- END SCRIPTS -->\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
