/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M10
 * Generated at: 2016-10-17 13:05:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import ro.dcmt.data.beans.Cabinet;
import ro.dcmt.data.beans.User;
import ro.dcmt.data.beans.Programare;
import ro.dcmt.data.beans.Pacient;
import ro.dcmt.data.beans.Operatie;
import ro.dcmt.data.controllers.CabinetService;
import ro.dcmt.data.controllers.ProgramariService;
import ro.dcmt.data.controllers.UserService;
import ro.dcmt.data.controllers.PacientService;
import ro.dcmt.data.controllers.OperatieService;
import java.util.ArrayList;
import java.util.Date;

public final class programare_002dnoua_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("ro.dcmt.data.beans.Cabinet");
    _jspx_imports_classes.add("ro.dcmt.data.beans.Pacient");
    _jspx_imports_classes.add("ro.dcmt.data.controllers.CabinetService");
    _jspx_imports_classes.add("ro.dcmt.data.beans.Programare");
    _jspx_imports_classes.add("ro.dcmt.data.beans.User");
    _jspx_imports_classes.add("ro.dcmt.data.controllers.UserService");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("ro.dcmt.data.controllers.PacientService");
    _jspx_imports_classes.add("ro.dcmt.data.controllers.OperatieService");
    _jspx_imports_classes.add("ro.dcmt.data.beans.Operatie");
    _jspx_imports_classes.add("ro.dcmt.data.controllers.ProgramariService");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<head>\n");

	String email = null;
	User currentUser = new User();
	Cabinet cabinet = new Cabinet();
	UserService us = new UserService();
	PacientService ps = new PacientService();
	CabinetService cs = new CabinetService();
	OperatieService os = new OperatieService();
	Cookie[] cookies = request.getCookies();
	ArrayList<Programare> programariNoi;
	ArrayList<Programare> programariViitoare;
	ArrayList<Operatie> operatiiCabinet = new ArrayList<Operatie>();
	if (cookies != null) {
		for (Cookie cookie : cookies) {
			if (cookie.getName().equals("user"))
				email = cookie.getValue();
		}
	} else {

		response.sendRedirect("login.jsp");
		return;

	}
	if (email == null) {

		response.sendRedirect("login.jsp");
		return;

	} else {

		currentUser = (User) us.getAllByColumn("email", email).get(0);
		cabinet = (Cabinet) cs.getById(currentUser.getId());

	}
	programariNoi = ProgramariService.getNewAppointmentsForDoctor(currentUser.getId());
	programariViitoare = ProgramariService.getFutureAppointments(currentUser.getId());
	operatiiCabinet = os.getOperatiiForCabinet(currentUser.getIdCabinet());

      out.write("\n");
      out.write("\n");
      out.write("<!-- META SECTION -->\n");
      out.write("<title>DCMT - ");
      out.print(currentUser.getFirstName() + " " + currentUser.getLastName());
      out.write("\n");
      out.write("\tinterfata de administrare\n");
      out.write("</title>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\n");
      out.write("\n");
      out.write("<link rel=\"icon\" href=\"favicon.ico\" type=\"image/x-icon\" />\n");
      out.write("<!-- END META SECTION -->\n");
      out.write("\n");
      out.write("<!-- CSS INCLUDE -->\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" id=\"theme\"\n");
      out.write("\thref=\"css/theme-default.css\" />\n");
      out.write("<!-- EOF CSS INCLUDE -->\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<!-- START PAGE CONTAINER -->\n");
      out.write("\t<div class=\"page-container\">\n");
      out.write("\n");
      out.write("\t\t<!-- START PAGE SIDEBAR -->\n");
      out.write("\t\t<div class=\"page-sidebar\">\n");
      out.write("\t\t\t<!-- START X-NAVIGATION -->\n");
      out.write("\t\t\t<ul class=\"x-navigation\">\n");
      out.write("\t\t\t\t<li class=\"xn-logo\"><a href=\"index.html\">DCMT</a> <a href=\"#\"\n");
      out.write("\t\t\t\t\tclass=\"x-navigation-control\"></a></li>\n");
      out.write("\t\t\t\t<li class=\"xn-profile\"><a href=\"#\" class=\"profile-mini\"> <img\n");
      out.write("\t\t\t\t\t\tsrc=\"");
      out.print(currentUser.getImagine().getName());
      out.write("\"\n");
      out.write("\t\t\t\t\t\talt=\"");
      out.print(currentUser.getFirstName());
      out.write("\" />\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t<div class=\"profile\">\n");
      out.write("\t\t\t\t\t\t<div class=\"profile-image\">\n");
      out.write("\t\t\t\t\t\t\t<img src=\"");
      out.print(currentUser.getImagine().getName());
      out.write("\"\n");
      out.write("\t\t\t\t\t\t\t\talt=\"");
      out.print(currentUser.getFirstName());
      out.write("\" />\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"profile-data\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"profile-data-name\">\n");
      out.write("\t\t\t\t\t\t\t\tDr.\n");
      out.write("\t\t\t\t\t\t\t\t");
      out.print(currentUser.getFirstName() + " " + currentUser.getLastName());
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"profile-data-title\">");
      out.print(cabinet.getNume());
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"profile-controls\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"javascript:void(0);\"\n");
      out.write("\t\t\t\t\t\t\t\tonclick=\"bootstro.start('.bootstro');\"\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"profile-control-left\"><span class=\"fa fa-info\"></span></a>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"bootstro.start('.bootstro');\"\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"profile-control-right\"><span class=\"fa fa-envelope\"></span></a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div></li>\n");
      out.write("\t\t\t\t<li class=\"xn-title\">Navigatie</li>\n");
      out.write("\t\t\t\t<li><a href=\"home.jsp\"><span class=\"fa fa-desktop\"></span>\n");
      out.write("\t\t\t\t\t\t<span class=\"xn-text\">Privire generala</span></a></li>\n");
      out.write("\t\t\t\t<li class=\"xn-openable active\"><a href=\"#\"><span\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-files-o\"></span> <span class=\"xn-text\">Pacienti</span></a>\n");
      out.write("\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"pacienti.jsp\"><span class=\"fa fa-users\"></span>\n");
      out.write("\t\t\t\t\t\t\t\tLista Pacienti </a></li>\n");
      out.write("\t\t\t\t\t\t<li class=\"active\"><a href=\"programare-noua.jsp\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-check-circle\"></span> Programare noua</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"calendar-programari.jsp\"><span\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"fa fa-calendar\"></span> Agenda programari</a></li>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t<li class=\"xn-openable\"><a href=\"#\"><span\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-file-text-o\"></span> <span class=\"xn-text\">Cabinet</span></a>\n");
      out.write("\t\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"layout-nav-top.html\">Agenda programari</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"layout-boxed.html\">Stoc produse</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"layout-nav-toggled.html\">Furnizori</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"layout-nav-top.html\">Plati utilitare</a></li>\n");
      out.write("\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t\n");
      out.write("\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t\t<!-- END X-NAVIGATION -->\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- END PAGE SIDEBAR -->\n");
      out.write("\n");
      out.write("\t\t<!-- PAGE CONTENT -->\n");
      out.write("\t\t<div class=\"page-content\">\n");
      out.write("\n");
      out.write("\t\t\t<!-- START X-NAVIGATION VERTICAL -->\n");
      out.write("\t\t\t<ul class=\"x-navigation x-navigation-horizontal x-navigation-panel\">\n");
      out.write("\t\t\t\t<!-- TOGGLE NAVIGATION -->\n");
      out.write("\t\t\t\t<li class=\"xn-icon-button\"><a href=\"#\"\n");
      out.write("\t\t\t\t\tclass=\"x-navigation-minimize\"><span class=\"fa fa-dedent\"></span></a>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t<!-- END TOGGLE NAVIGATION -->\n");
      out.write("\t\t\t\t<!-- SEARCH -->\n");
      out.write("\t\t\t\t<li class=\"xn-search\">\n");
      out.write("\t\t\t\t\t<form role=\"form\">\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"search\" placeholder=\"Cauta pacienti...\" />\n");
      out.write("\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t</li>\n");
      out.write("\t\t\t\t<!-- END SEARCH -->\n");
      out.write("\t\t\t\t<!-- SIGN OUT -->\n");
      out.write("\t\t\t\t<li class=\"xn-icon-button pull-right\"><a href=\"#\"\n");
      out.write("\t\t\t\t\tclass=\"mb-control\" data-box=\"#mb-signout\"><span\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-sign-out\"></span></a></li>\n");
      out.write("\t\t\t\t<!-- END SIGN OUT -->\n");
      out.write("\t\t\t\t<!-- MESSAGES -->\n");
      out.write("\t\t\t\t<li class=\"xn-icon-button pull-right bootstro\"\n");
      out.write("\t\t\t\t\tdata-bootstro-title=\"Programari neaprobate\"\n");
      out.write("\t\t\t\t\tdata-bootstro-placement=\"bottom\"\n");
      out.write("\t\t\t\t\tdata-bootstro-content=\"Aici veti gasi programarile nou create si neaprobate.\"\n");
      out.write("\t\t\t\t\tdata-bootstro-step=\"5\"><a href=\"#\"><span\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-calendar-check-o\"></span></a>\n");
      out.write("\t\t\t\t\t<div class=\"informer informer-danger\">");
      out.print(programariNoi.size());
      out.write("</div>\n");
      out.write("\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\tclass=\"panel panel-primary animated zoomIn xn-drop-left xn-panel-dragging\">\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-heading\">\n");
      out.write("\t\t\t\t\t\t\t<h3 class=\"panel-title\">\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"fa fa-calendar-check-o\"></span> Programari noi\n");
      out.write("\t\t\t\t\t\t\t</h3>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"pull-right\">\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"label label-danger\">");
      out.print(programariNoi.size());
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\tneaprobate</span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-body list-group list-group-contacts scroll\"\n");
      out.write("\t\t\t\t\t\t\tstyle=\"height: 200px;\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t");

								Pacient pacientProgramare;
								for (Programare p : programariNoi) {

									pacientProgramare = (Pacient) ps.getById(p.getIdUser());
							
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<a href=\"pacient.jsp?id=");
      out.print(pacientProgramare.getId());
      out.write("\"\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"list-group-item\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"list-group-status status-online\"></div> <img\n");
      out.write("\t\t\t\t\t\t\t\tsrc=\"");
      out.print(pacientProgramare.getImagine().getName());
      out.write("\"\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"pull-left\" alt=\"");
      out.print(pacientProgramare.getFirstName());
      out.write("\" />\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"contacts-title\">");
      out.print(pacientProgramare.getFirstName() + " " + pacientProgramare.getLastName());
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t\t\t<p>");
      out.print(p.getIdOperatii());
      out.write("</p>\n");
      out.write("\t\t\t\t\t\t\t</a>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t");

								}
							
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-footer text-center\">\n");
      out.write("\t\t\t\t\t\t\t<a href=\"pages-messages.html\">Vezi toate programarile</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div></li>\n");
      out.write("\t\t\t\t<!-- END MESSAGES -->\n");
      out.write("\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t\t<!-- END X-NAVIGATION VERTICAL -->\n");
      out.write("\n");
      out.write("\t\t\t<!-- START BREADCRUMB -->\n");
      out.write("\t\t\t<ul class=\"breadcrumb\">\n");
      out.write("\t\t\t\t<li><a href=\"#\">Acasa</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"#\">Pacienti</a></li>\n");
      out.write("\t\t\t\t<li class=\"active\">Programare noua</li>\n");
      out.write("\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t\t<!-- END BREADCRUMB -->\n");
      out.write("\n");
      out.write("\t\t\t<!-- PAGE CONTENT WRAPPER -->\n");
      out.write("\t\t\t<div class=\"page-content-wrap\">\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<form class=\"form-horizontal\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"panel panel-default\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"panel-heading\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3 class=\"panel-title\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\tFormular <strong>programare noua</strong>\n");
      out.write("\t\t\t\t\t\t\t\t\t</h3>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"panel-body\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Folositi acest formular pentru a crea o programare noua</p>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"panel-body\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"col-md-3 col-xs-12 control-label\">Nume Complet\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tPacient (\"Prenume Nume\")</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6 col-xs-12\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"input-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"numePacient\" class=\"form-control\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"eg. Ion Popescu\"> <span\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"input-group-btn\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-default\" type=\"button\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tonClick=\"javascript:searchPacient()\">Cauta\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tpacient</button>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-default\" type=\"button\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata-toggle=\"modal\" data-target=\"#modalAdaugaPacient\">Adauga\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tpacient</button>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"help-block\">Folositi butonul \"Cauta\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tpacient\" pentru a-l cauta in pacientii existenti</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"col-md-3 col-xs-12 control-label\">Data\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tprogramarii</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6 col-xs-12\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"input-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"input-group-addon\"><span\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fa fa-calendar\"></span></span> <input type=\"text\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control datepicker\" id=\"dataProgramare\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"2016-11-01\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"help-block\">Click pe casuta pentru a\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tafisa calendarul</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"col-md-3 col-xs-12 control-label\">Ora\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tprogramarii</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6 col-xs-12\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"input-group bootstrap-timepicker\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"timpProgramare\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control timepicker24\"> <span\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"input-group-addon\"><span\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-time\"></span></span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"help-block\">Click pe casuta pentru a\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tafisa ceasul </span>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"hidden\" value=\"");
      out.print(currentUser.getId());
      out.write("\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\tid=\"doctorID\" />\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"col-md-3 col-xs-12 control-label\">Operatii</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6 col-xs-12\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<select multiple id=\"operatiiProgramare\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control select\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");

													for (Operatie o : operatiiCabinet) {
												
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print(o.getId());
      out.write('"');
      out.write('>');
      out.print(o.getTitlu());
      out.write("</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");

													}
												
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"col-md-3 col-xs-12 control-label\">Comentariul\n");
      out.write("\t\t\t\t\t\t\t\t\t\tprogramarii</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-6 col-xs-12\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<textarea class=\"form-control\" rows=\"5\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"comentariuProgramare\"></textarea>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"help-block\">Adauga comentarii pentru\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\taceasta programare</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<label class=\"col-md-3 col-xs-12 control-label\">Notificari\n");
      out.write("\t\t\t\t\t\t\t\t\t\tpacient</label>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-6 col-xs-12\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label class=\"check\"> <input type=\"checkbox\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"icheckbox\" checked=\"checked\" id=\"notificationMobile\" />\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tDentistul Meu Mobile App\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</label> <label class=\"check\" id=\"phoneNumber\"> <input\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"checkbox\" class=\"icheckbox\" checked=\"checked\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"notificationSMS\" /> SMS\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</label> <label class=\"check\" id=\"pacientEmail\"> <input\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\ttype=\"checkbox\" class=\"icheckbox\" checked=\"checked\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"notificationEmail\" /> Email\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</label> <span class=\"help-block\">Selectati tipurile de\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tnotificari pentru pacient</span>\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-footer\">\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-default\">Sterge campurile</button>\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-primary pull-right\"\n");
      out.write("\t\t\t\t\t\t\t\tonClick=\"javascript:createAppointment()\">Salveaza\n");
      out.write("\t\t\t\t\t\t\t\tprogramarea</button>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- END PAGE CONTENT WRAPPER -->\n");
      out.write("\t</div>\n");
      out.write("\t<!-- END PAGE CONTENT -->\n");
      out.write("\t</div>\n");
      out.write("\t<!-- END PAGE CONTAINER -->\n");
      out.write("\n");
      out.write("\t<!-- MESSAGE BOX-->\n");
      out.write("\t<div class=\"message-box animated fadeIn\" data-sound=\"alert\"\n");
      out.write("\t\tid=\"mb-signout\">\n");
      out.write("\t\t<div class=\"mb-container\">\n");
      out.write("\t\t\t<div class=\"mb-middle\">\n");
      out.write("\t\t\t\t<div class=\"mb-title\">\n");
      out.write("\t\t\t\t\t<span class=\"fa fa-sign-out\"></span> Log <strong>Out</strong> ?\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"mb-content\">\n");
      out.write("\t\t\t\t\t<p>Esti sigur ca vrei sa te deloghezi?</p>\n");
      out.write("\t\t\t\t\t<p>Apasa DA daca vrei sa confirmi sau NU pentru a continua\n");
      out.write("\t\t\t\t\t\tsesiunea de lucru.</p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"mb-footer\">\n");
      out.write("\t\t\t\t\t<div class=\"pull-right\">\n");
      out.write("\t\t\t\t\t\t<a href=\"logout.jsp\" class=\"btn btn-success btn-lg\">Da</a>\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-default btn-lg mb-control-close\">Nu</button>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- END MESSAGE BOX-->\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<!--  MODAL ADD PATIENT -->\n");
      out.write("\t<div class=\"modal\" id=\"modalAdaugaPacient\" tabindex=\"-1\" role=\"dialog\"\n");
      out.write("\t\taria-labelledby=\"defModalHead\" aria-hidden=\"true\"\n");
      out.write("\t\tstyle=\"display: none;\">\n");
      out.write("\t\t<div class=\"modal-dialog\">\n");
      out.write("\t\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t\t<div class=\"modal-body\">\n");
      out.write("\t\t\t\t\t<h3>Modal without head</h3>\n");
      out.write("\t\t\t\t\t<form class=\"form-horizontal\" role=\"form\">\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t<label class=\"col-md-2 control-label\">Prenume</label>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-10\">\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Ion\" id=\"prenumePacientModal\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t<label class=\"col-md-2 control-label\">Nume de familie</label>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-10\">\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Popescu\" id=\"numePacientModal\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t<label class=\"col-md-2 control-label\">Oras</label>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-10\">\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Bucuresti\" id=\"orasPacient\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t<label class=\"col-md-2 control-label\">Email</label>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-10\">\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\"\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"ion.popescu@gmail.com\" id=\"emailPacient\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t\t<label class=\"col-md-2 control-label\">Numar de telefon</label>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-10\">\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\"\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"0722 222 222\" id=\"numarTelefonPacient\">\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"modal-footer\">\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Inchide</button>\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-default\"\n");
      out.write("\t\t\t\t\t\tonClick=\"javascript:addPatient();\">Salveaza pacient</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<!-- END MODAL ADD PATIENT -->\n");
      out.write("\n");
      out.write("\t<!-- START PRELOADS -->\n");
      out.write("\t<audio id=\"audio-alert\" src=\"audio/alert.mp3\" preload=\"auto\"></audio>\n");
      out.write("\t<audio id=\"audio-fail\" src=\"audio/fail.mp3\" preload=\"auto\"></audio>\n");
      out.write("\t<!-- END PRELOADS -->\n");
      out.write("\n");
      out.write("\t<!-- START SCRIPTS -->\n");
      out.write("\t<!-- START PLUGINS -->\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/plugins/jquery/jquery.min.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/plugins/jquery/jquery-ui.min.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\"\n");
      out.write("\t\tsrc=\"js/plugins/bootstrap/bootstrap.min.js\"></script>\n");
      out.write("\t<!-- END PLUGINS -->\n");
      out.write("\n");
      out.write("\t<!-- THIS PAGE PLUGINS -->\n");
      out.write("\t<script type='text/javascript' src='js/plugins/icheck/icheck.min.js'></script>\n");
      out.write("\t<script type=\"text/javascript\"\n");
      out.write("\t\tsrc=\"js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\"\n");
      out.write("\t\tsrc=\"js/plugins/bootstrap/bootstrap-timepicker.min.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\"\n");
      out.write("\t\tsrc=\"js/plugins/bootstrap/bootstrap-datepicker.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\"\n");
      out.write("\t\tsrc=\"js/plugins/bootstrap/bootstrap-file-input.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\"\n");
      out.write("\t\tsrc=\"js/plugins/bootstrap/bootstrap-select.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\"\n");
      out.write("\t\tsrc=\"js/plugins/tagsinput/jquery.tagsinput.min.js\"></script>\n");
      out.write("\t<!-- END THIS PAGE PLUGINS -->\n");
      out.write("\n");
      out.write("\t<!-- START TEMPLATE -->\n");
      out.write("\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/programare.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/plugins.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/actions.js\"></script>\n");
      out.write("\t<!-- END TEMPLATE -->\n");
      out.write("\t<!-- END SCRIPTS -->\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
